// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-hwHbPUYhMwUn44UCX1euEH0hgJ2STcQ',
    appId: '1:1069814630936:web:93cde3347b16529077516d',
    messagingSenderId: '1069814630936',
    projectId: 'flexi-b37db',
    authDomain: 'flexi-b37db.firebaseapp.com',
    storageBucket: 'flexi-b37db.appspot.com',
    measurementId: 'G-3BL9NQDZZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkE3glwM202-6r0dcUCLvWk_DY_2tPvs',
    appId: '1:1069814630936:android:3dea44b38b1da00b77516d',
    messagingSenderId: '1069814630936',
    projectId: 'flexi-b37db',
    storageBucket: 'flexi-b37db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59ZzeVz4xqihQEncqb5K6Vf9PpGVGmfM',
    appId: '1:1069814630936:ios:3fc2d5d25b17cba577516d',
    messagingSenderId: '1069814630936',
    projectId: 'flexi-b37db',
    storageBucket: 'flexi-b37db.appspot.com',
    androidClientId: '1069814630936-3tad1nbfogj50qsfvj78rd19223q7mku.apps.googleusercontent.com',
    iosClientId: '1069814630936-kiau2cjjiipfmue55dsge7vr063g9f8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59ZzeVz4xqihQEncqb5K6Vf9PpGVGmfM',
    appId: '1:1069814630936:ios:3fc2d5d25b17cba577516d',
    messagingSenderId: '1069814630936',
    projectId: 'flexi-b37db',
    storageBucket: 'flexi-b37db.appspot.com',
    androidClientId: '1069814630936-3tad1nbfogj50qsfvj78rd19223q7mku.apps.googleusercontent.com',
    iosClientId: '1069814630936-kiau2cjjiipfmue55dsge7vr063g9f8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-hwHbPUYhMwUn44UCX1euEH0hgJ2STcQ',
    appId: '1:1069814630936:web:b6cef1a5553f7b7477516d',
    messagingSenderId: '1069814630936',
    projectId: 'flexi-b37db',
    authDomain: 'flexi-b37db.firebaseapp.com',
    storageBucket: 'flexi-b37db.appspot.com',
    measurementId: 'G-ZPYE7K7W3D',
  );

}